---
platform: hdc1080
temperature:
  name: ${node_friendly_name} Temperature
  id: temperature_sensor_2
humidity:
  name: ${node_friendly_name} Humidity
  id: humidity_sensor_2
update_interval: ${global_update_interval}
i2c_id: bus_a
...