---
platform: sps30
pm_1_0:
  name: ${node_friendly_name} PM <1µm Weight concentration
  id: PM1
pm_2_5:
  name: ${node_friendly_name} PM <2.5µm Weight concentration
  id: PM25
pm_4_0:
  name: ${node_friendly_name} PM <4µm Weight concentration
  id: PM40
pm_10_0:
  name: ${node_friendly_name} PM <10µm Weight concentration
  id: PM10
pmc_0_5:
  name: ${node_friendly_name} PM <0.5µm Number concentration
  id: PMC05
pmc_1_0:
  name: ${node_friendly_name} PM <1µm Number concentration
  id: PMC1
pmc_2_5:
  name: ${node_friendly_name} PM <2.5µm Number concentration
  id: PMC25
pmc_4_0:
  name: ${node_friendly_name} PM <4µm Number concentration
  id: PMC40
pmc_10_0:
  name: ${node_friendly_name} PM <10µm Number concentration
  id: PMC10
address: 0x69
update_interval: ${global_update_interval}
i2c_id: bus_a
...