---
#####################################################
###################### GENERAL ######################
#####################################################
substitutions:
  node_platform: ESP32
  node_board: esp-wrover-kit

######################### CUSTOM #########################
esphome:
  includes:
    - ../esphome/common/custom/dsmr_p1_uart.h
  libraries:
    - "Dsmr"

######################### PACKAGES #########################
packages:
  device_base: !include ../common/device_base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

######################### LOGGING #########################
#status_led:
#  pin:
#    number: GPIO2
#    inverted: True #Normally off

####################################################################
###################### DETAILED CONFIGURATION ######################
####################################################################

######################### UART #########################
uart:
  - rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 115200
    uart_invert: True
    data_bits: 8
    parity: NONE
    stop_bits: 1
    #rx_buffer_size: 256
    id: p1_bus    

######################### LIGHT #########################
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO04
    num_leds: 3
    rgb_order: GRB
    name: $node_friendly_name Light
    effects:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_color_wipe:

######################### OUTPUT #########################
output:
  - platform: ledc
    pin: GPIO14
    frequency: 2441Hz
    id: rtttl_buzzer

######################### RTTTL #########################
rtttl:
  output: rtttl_buzzer

######################### SWITCH #########################
#switch:
#  - platform: gpio
#    name: $node_friendly_name REQ
#    pin:
#      number: GPIO023

######################### BINARY SENSORS #########################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      #mode: INPUT_PULLUP
      inverted: True
    name: $node_friendly_name Button 1
    on_press:
      then:
        - rtttl.play: 'MissionImp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'
  - platform: gpio
    pin:
      number: GPIO13
      #mode: INPUT_PULLUP
      inverted: True
    name: $node_friendly_name Button 2
    on_press:
      then:
        - rtttl.stop

######################### SENSORS #########################
sensor:
  - platform: pulse_counter
    pin: GPIO19
    unit_of_measurement: 'L'
    name: $node_friendly_name water usage 1
    filters:
      - multiply: 0.0001
  - platform: pulse_counter
    pin: GPIO18
    unit_of_measurement: 'L'
    name: $node_friendly_name water usage 2
    filters:
      - multiply: 0.0001

######################### CUSTOM COMPONENT #########################
#  - platform: custom
#    lambda: |-
#      auto dsmr_p1_sensor = new CustomP1UartComponent(id(p1_bus));
#      App.register_component(dsmr_p1_sensor);
#      return {dsmr_p1_sensor->s_energy_delivered_tariff1, dsmr_p1_sensor->s_energy_delivered_tariff2, dsmr_p1_sensor->s_energy_returned_tariff1, dsmr_p1_sensor->s_energy_returned_tariff2, dsmr_p1_sensor->s_power_delivered, dsmr_p1_sensor->s_power_returned, dsmr_p1_sensor->s_voltage_l1, dsmr_p1_sensor->s_voltage_l2, dsmr_p1_sensor->s_voltage_l3, dsmr_p1_sensor->s_current_l1, dsmr_p1_sensor->s_current_l2, dsmr_p1_sensor->s_current_l3, dsmr_p1_sensor->s_power_delivered_l1, dsmr_p1_sensor->s_power_delivered_l2, dsmr_p1_sensor->s_power_delivered_l3, dsmr_p1_sensor->s_power_returned_l1, dsmr_p1_sensor->s_power_returned_l2, dsmr_p1_sensor->s_power_returned_l3, dsmr_p1_sensor->s_gas_device_type, dsmr_p1_sensor->s_gas_valve_position, dsmr_p1_sensor->s_gas_delivered};

  - platform: custom
    lambda: |-
      auto dsmr_p1_sensor = new CustomP1UartComponent(id(p1_bus));
      App.register_component(dsmr_p1_sensor);
      return {dsmr_p1_sensor->s_energy_delivered_tariff1, dsmr_p1_sensor->s_energy_delivered_tariff2, dsmr_p1_sensor->s_energy_returned_tariff1, dsmr_p1_sensor->s_energy_returned_tariff2, dsmr_p1_sensor->s_power_delivered, dsmr_p1_sensor->s_power_returned, dsmr_p1_sensor->s_voltage_l1, dsmr_p1_sensor->s_voltage_l2, dsmr_p1_sensor->s_voltage_l3, dsmr_p1_sensor->s_current_l1, dsmr_p1_sensor->s_current_l2, dsmr_p1_sensor->s_current_l3, dsmr_p1_sensor->s_power_delivered_l1, dsmr_p1_sensor->s_power_delivered_l2, dsmr_p1_sensor->s_power_delivered_l3, dsmr_p1_sensor->s_power_returned_l1, dsmr_p1_sensor->s_power_returned_l2, dsmr_p1_sensor->s_power_returned_l3, dsmr_p1_sensor->s_gas_device_type, dsmr_p1_sensor->s_gas_valve_position, dsmr_p1_sensor->s_gas_delivered};
    sensors:
    - name: "$node_friendly_name Consumption Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "$node_friendly_name Consumption High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3  
    - name: "$node_friendly_name Return Low Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "$node_friendly_name Return High Tarif Sensor"
      unit_of_measurement: kWh
      accuracy_decimals: 3  
    - name: "$node_friendly_name Actual Consumption Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Actual Delivery Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Instant Voltage L1 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3      
    - name: "$node_friendly_name Instant Voltage L2 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3      
    - name: "$node_friendly_name Instant Voltage L3 Sensor"
      unit_of_measurement: V
      accuracy_decimals: 3      
    - name: "$node_friendly_name Instant Current L1 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3      
    - name: "$node_friendly_name Instant Current L2 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3      
    - name: "$node_friendly_name Instant Current L3 Sensor"
      unit_of_measurement: A
      accuracy_decimals: 3      
    - name: "$node_friendly_name Power Delivered L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Power Delivered L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Power Delivered L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Power Returned L1 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Power Returned L2 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Power Returned L3 Sensor"
      unit_of_measurement: W
      accuracy_decimals: 3      
      filters:
        - multiply: 1000
    - name: "$node_friendly_name Gas device type Sensor"
    - name: "$node_friendly_name Gas valve position Sensor"  
    - name: "$node_friendly_name Gas Meter M3 Sensor"
      unit_of_measurement: m3
      accuracy_decimals: 3
...