---
#####################################################
###################### GENERAL ######################
#####################################################
substitutions:
  node_platform: ESP32
  node_board: esp-wrover-kit

######################### PACKAGES #########################
packages:
  device_base: !include ../common/device_base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml
  disable_sleep: !include ../common/binary_sensor/disable_sleep.yaml

######################### DEEP SLEEP #########################
deep_sleep:
  run_duration: ${deep_sleep_runtime}
  sleep_duration: ${deep_sleep_sleepime}
  wakeup_pin:
    number: GPIO35
    inverted: True
    mode: INPUT_PULLUP
  id: deep_sleep_1

esphome:
  on_shutdown:
    then:
      - switch.turn_off: spower

######################### LOGGING #########################
status_led:
  pin:
    number: GPIO27
    inverted: False #Normally off

####################################################################
###################### DETAILED CONFIGURATION ######################
####################################################################

######################### LIGHT #########################
light:
  - platform: binary
    name: "${node_friendly_name} OTA Indicator"
    output: gpio_23
    internal: True
    id: ota_indicator

######################### OUTPUT #########################
# OTA indicator LED
output:
  - platform: gpio
    pin: GPIO23
    id: gpio_23

######################### I2C #########################
i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a

######################### SWITCH #########################
switch:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: False
      mode: OUTPUT
    name: "${node_friendly_name} Sensor Power"
    id: spower
    restore_mode: ALWAYS_ON
    internal: true

######################### BINARY SENSORS #########################
# Prevent deep sleep button
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO35
      mode: INPUT_PULLUP
      inverted: True
    id: disable_sleep_button
    name: "${node_friendly_name} Wake + disable sleep Button"
    internal: true
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.esphome_ota_enable
        - logger.log: "Toggleing input_boolean.esphome_ota_enable value"
#        - logger.log: "Preventing deep sleep, user (button) activated"
#        - deep_sleep.prevent: deep_sleep_1
#        - switch.turn_on: spower
        - light.toggle:
            id: ota_indicator

######################### SENSORS #########################
sensor:
  - platform: dht
    model: dht11
    pin:
      number: GPIO16
      mode: input
    temperature:
      name: "${node_friendly_name} Temperature"
    humidity:
      name: "${node_friendly_name} Humidity"
    update_interval: ${global_update_interval}
    setup_priority: -100
    
  - platform: adc
    pin: GPIO33
    name: "${node_friendly_name} Battery"
    attenuation: 11db
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: mdi:battery-charging
    update_interval: ${global_update_interval}
    filters:
      - calibrate_linear:
          #- 0.0 -> 0.0
          - ${battcallmin} -> 0.0
          - ${battcallmax} -> 100
    
  - platform: adc
    pin: GPIO32
    name: "${node_friendly_name} Soil Humidity"
    attenuation: 11db
    update_interval: ${global_update_interval}
    unit_of_measurement: '%'
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 1
          send_first_at: 1
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${soilmoistmin} -> 0.0
          - ${soilmoistmax} -> 100.0
        
  - platform: adc
    pin: GPIO34
    name: "${node_friendly_name} Soil Salt"
    attenuation: 0db
    update_interval: ${global_update_interval}
    unit_of_measurement: '%'
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 1
          send_first_at: 1
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${soilsaltmin} -> 0.0
          - ${soilsaltmax} -> 100.0
    
  - platform: bh1750
    name: "${node_friendly_name} Illuminance"
    address: 0x23
    i2c_id: bus_a
    update_interval: ${global_update_interval}
    setup_priority: -100
...