---
######################### GENERAL #########################
substitutions:
  node_name: esp32_universal
  node_friendly_name: ESP32 Universal
  comment: Universal base firmware for th ESP32 with OTA update capabilities

  # Time settings
  reboot_timeout: 10min
  global_update_interval: 10sec

######################### PACKAGES #########################
packages:
  device_base: !include devices/esp32.yaml

######################### WIFI #########################
#wifi:
#  # Optional manual IP
#  manual_ip:
#    static_ip: 192.168.178.xx
#    gateway: 192.168.178.1
#    subnet: 255.255.255.0

######################### LOGGER #########################
logger:
  level: INFO
...