---
######################### GENERAL #########################
substitutions:
  node_name: sonoff_rf_ir
  node_friendly_name: SonOff RF IR
  friendly_id: SonOff_RF_IR
  comment: SonOff RF r2 with additional IR led and wireless mcu programming port connected to esp8266
  # Time settings
  reboot_timeout: 15min
  global_update_interval: 60sec

######################### PACKAGES #########################
packages:
  device_base: !include common/device_base.yaml

######################### DEVICE SETTINGS #########################
esphome:
  platform: ESP8266
  board: esp8285

#wifi:
  # Optional manual IP
#  manual_ip:
#    static_ip: 192.168.178.31
#    gateway: 192.168.178.1
#    subnet: 255.255.255.0

######################### LOGGING #########################
logger:
  baud_rate: 0 # disable UART logging
#  level: NONE
#  level: ERROR
#  level: WARN
#  level: INFO
  level: DEBUG
#  level: VERBOSE
#  level: VERY_VERBOSE

status_led:
  pin:
    number: GPIO13
    inverted: False #Normally off

####################################################################
###################### DETAILED CONFIGURATION ######################
####################################################################

######################### BINARY SENSORS #########################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      #mode: INPUT_PULLUP
      inverted: True
    name: "$node_friendly_name Learn"
    #internal: True
    on_press:
      then:
        - rf_bridge.learn
        - remote_transmitter.transmit_panasonic:
            address: 0x4004
            command: 0x100BCBD

######################### API #########################
api:
  services:
    - service: send_rf_code
      variables:
        sync: int
        low: int
        high: int
        code: int
      then:
        - rf_bridge.send_code:
            sync: !lambda 'return sync;'
            low: !lambda 'return low;'
            high: !lambda 'return high;'
            code: !lambda 'return code;'
    - service: learn
      then:
        - rf_bridge.learn

######################### SonOff RF bridge #########################
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200

rf_bridge:
  on_code_received:
    then:
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            sync: !lambda 'char buffer [10];return itoa(data.sync,buffer,16);'
            low: !lambda 'char buffer [10];return itoa(data.low,buffer,16);'
            high: !lambda 'char buffer [10];return itoa(data.high,buffer,16);'
            code: !lambda 'char buffer [10];return itoa(data.code,buffer,16);'


######################### SENSORS #########################
sensor:

######################### TEXT SENSORS #########################
text_sensor:

######################### IR REMOTE TRANSMITTER #########################
remote_transmitter:
  pin:
    number: GPIO14
    inverted: False
    mode: OUTPUT
  carrier_duty_percent: 50%
...